//
//  DatabaseService.swift
//  TaskIt
//
//  Created by Robert Wais on 7/24/18.
//

import Foundation
import FirebaseDatabase


struct DatabaseService {
//    // Generate a reference to a new location and add some data using push()
//    var newPostRef = postsRef.push({
//        author: "gracehop",
//        title: "Announcing COBOL, a New Programming Language"
//    });
//    // Get the unique ID generated by push() by accessing its key
//    var postID = newPostRef.key;
//
    static func createCompany(uniqueId: String, name: String, sender: UIViewController,completion: @escaping (Bool)->()){
        let ref = Database.database().reference().child("company").childByAutoId()
        
        
        let companyInfo = ["name" : name]
        
        ref.setValue(companyInfo) { (error, ref) in
            if let error = error {
                Alerts.simpleAlert(err: error, controller: sender)
                completion(false)
            }else{
                Alerts.displayKey(uniqueID: "\(ref.key)", sender: sender, finished: {
                    completion(true)
                    print("Closed")
                })
            }
           
        }
    }
    
}
