//
//  DatabaseService.swift
//  TaskIt
//
//  Created by Robert Wais on 7/24/18.
//

import Foundation
import FirebaseDatabase


struct DatabaseService {
    
    private static let mainRef = Database.database().reference()
    static let companyRef = mainRef.child("company").child(TaskUser.current.companyID)

    static func createCompany(uniqueId: String, name: String, sender: UIViewController,completion: @escaping (Bool)->()){
        let ref = Database.database().reference().child("company").childByAutoId()
        let companyInfo = ["name" : name]
        ref.setValue(companyInfo) { (error, ref) in
            if let error = error {
                Alerts.simpleAlert(err: error, controller: sender)
                completion(false)
            }else{
                Alerts.displayKey(uniqueID: "\(ref.key)", sender: sender, finished: {
                    completion(true)
                    print("Closed")
                })
            }
        }
    }
    
    static func makeAPost(){
        //Two Functions
        //1) Update User Posts
        //2) Update company array of tasks
    }
    
    static func updateArryOfTasks(task: Task,sender: UIViewController, completion: @escaping (Bool)->()){
        let ref = companyRef.child("currentTasks").childByAutoId().child(task.title)
        let indyRef = mainRef.child("users").child(TaskUser.current.uid).child("completed")
        ref.setValue(task) { (error, ref) in
            if let err = error {
                Alerts.simpleAlert(err: err, controller: sender)
                completion(false)
                return
            }
            completion(true)
        }
    }
}

//    Database.database().reference().child("company").child(TaskUser.current.companyID)
//    // Generate a reference to a new location and add some data using push()
//    var newPostRef = postsRef.push({
//        author: "gracehop",
//        title: "Announcing COBOL, a New Programming Language"
//    });
//    // Get the unique ID generated by push() by accessing its key
//    var postID = newPostRef.key;
//
